# 데이터 분석을 위한 Python 라이브러리
---

1. Matplotlib
    - 데이터 시각화
2. Numpy
    - 행렬, 수치 계산 등 데이터를 다루기 쉽게 도와줌
    - 튜토리얼: https://numpy.org/devdocs/user/quickstart.html
3. Pandas
    - 테이블 형태의 데이터를 다루기 쉽게 도와주는 라이브러리
    - 튜토리얼: https://pandas.pydata.org/pandas-docs/stable/getting_started/intro_tutorials/index.html

# Numpy란?
---
- 행렬, 수치 계산 등 데이터를 다루기 쉽게 도와줌
    - 튜토리얼: https://numpy.org/devdocs/user/quickstart.html
- 다차원 배열 구조인 ndarray를 이용하여 행렬/벡터 및 수치 연산을 빠르게 하는 것이 핵심
- numpy array의 연산 속도 차이는 30~40배까지 나기도 함
- 데이터의 크기가 커질수록 numpy는 필수
- `import numpy as np`

## Numpy의 핵심은 ndarray
- `np.array()` 는 리스트, 튜플, 배열로 부터 ndarray를 생성

In [1]:
import numpy as np

# 1차원 배열 생성
a = np.array([1,2,3,4,5])
print(type(a))
print(a)

<class 'numpy.ndarray'>
[1 2 3 4 5]


In [2]:
# 2차원 배열 생성
a2 = np.array([[1,2,3], [4,5,6]])
print(a2)

[[1 2 3]
 [4 5 6]]


### 배열의 차원 및 크기 확인

-ndim 및 shape 속성으로 출력하기

In [4]:
print(a2.ndim) # a2의 차원(dimension)
print(a2.shape) # a2의 행렬

2
(2, 3)


# Numpy
---

1. ndarray 초기화 방법들
2. 슬라이싱 (Slicing)
3. Numpy 연산
4. Numpy array와 list 차이

## 1. ndarray 초기화 방법들

- 리스트를 이용하여 ndarray 생성하기
- 그 외에 다양한 방법들

        np.zeros((a, b))
        np.ones((a, b))
        np.full((a, b), c))
        np.eye(a)
        np.random.random(a, b)
        ...

### np.zeros(shape = (a, b))

- 모든 값이 0인 a \* b 크기의 배열 생성

### np.ones((a, b))

### np.full((a, b), c))

### np.eye(a)

### np.random.random(a, b)