# Numpy란?
---
- 행렬, 수치 계산 등 데이터를 다루기 쉽게 도와줌
    - 튜토리얼: https://numpy.org/devdocs/user/quickstart.html
    
    
- 다차원 배열 구조인 ndarray를 이용하여 행렬/벡터 및 수치 연산을 빠르게 하는 것이 핵심


- numpy array의 연산 속도 차이는 30~40배까지 나기도 함


- 데이터의 크기가 커질수록 numpy는 필수


- `import numpy as np`

## Numpy의 핵심은 ndarray
- `np.array()` 는 리스트, 튜플, 배열로 부터 ndarray를 생성

In [1]:
import numpy as np

# 1차원 배열 생성
a = np.array([1,2,3,4,5])
print(type(a))
print(a)

<class 'numpy.ndarray'>
[1 2 3 4 5]


In [2]:
# 2차원 배열 생성
a2 = np.array([[1,2,3], [4,5,6]])
print(a2)

[[1 2 3]
 [4 5 6]]


### 배열의 차원 및 크기 확인

-ndim 및 shape 속성으로 출력하기

In [4]:
print(a2.ndim) # a2의 차원(dimension)
print(a2.shape) # a2의 행렬

2
(2, 3)


# Numpy
---

1. ndarray 초기화 방법들
2. 슬라이싱 (Slicing)
3. Numpy 연산
4. Numpy array와 list 차이

## 1. ndarray 초기화 방법들

- 리스트를 이용하여 ndarray 생성하기
- 그 외에 다양한 방법들

### np.zeros((a, b))

- 모든 값이 0인 a \* b 크기의 배열 생성

### np.ones((a, b))

- 모든 값이 1인 a \* b 크기인 배열 생성

### np.full((a, b), x))

- 모든 값이 x인 a \* b 크기인 배열 생성

### np.eye(a)

- 대각선 값이 1이고 나머지는 0인 a \* a 크기의 2차원 배열 생성
- 만약 np.eye(a, b) 인 경우 a \* b 크기의 2차원 배열 생성

In [6]:
aeye = np.eye(3)
aeye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### np.random.randn(a, b)

- 임의의 값으로 채워진 a \* b 크기인 배열 생성
- numpy.random.randn(d0, d1, ..., dn)

## 2. 슬라이싱 (Slicing)

- ndarray를 통해 만든 다차원 배열은 list처럼 슬라이스(Slice)


In [11]:
a = np.array([0,1,2,3,4,5])
a[1:3]

a2 = np.array([[1,2,3], [4,5,6]])
a2[0:2, 0:2]

[1 2]
[[1 2]
 [4 5]]


## 3. Numpy 연산

- Numpy로 만든 자료형은 자유롭게 사칙 연산 가능


- 배열 간 연산을 손쉽게 수행할 수 있음


    - `+`, `-`, `*`, `/` 연산자 사용
    - `add()`, `substract()`, `multiply()`, `divide()` 함수 사용

In [18]:
a = np.array([1,2,3])
b = np.array([4,5,6])

c = a + b
print('c ', c)

d = a + 5

print('d ', d)

c  [5 7 9]
d  [6 7 8]
